module.exports={
    PRODUCT_COLLECTION:"product",
    USER_COLLECTION:"user",
    ADMIN_COLLECTION:"admin",
    CATAGORY_COLLECTION:"catagory",
    CART_COLLECTION:"cart",
    ADDRESS_COLLECTION:"address",
    ORDER_COLLECTION:"orders",
    WISHLIST_COLLECTION:"wishlist",
    COMMON_CUPON_COLLECTION:"cupon",
    PRODUCT_OFFER_COLLECTION:"productOffers",
    CATAGORY_OFFER_COLLECTION:"catagoryOffers",
}